### ISSUE TITLE
Don't save last session if last session doesn't need to be saved.

### ISSUE THREAD

**Issue by crocket** [tvrzna/emptty#10]
I discovered that last session is saved to disk whenever I enter a GUI session.

If the last session is the same as the current session I'm trying to enter, we can save a write cycle.

I also suggest saving last session in `~/.local` or `~/.cache` instead of `/etc/emptty/last-sessions`

**Comment by tvrzna** [comment]
I agree, that repeated save shoud be fixed.

I understand also why you suggest the relocation, `/etc/` folder is not really good place to keep this kind of data, I'll think about possible solution, before I start with spreading of new files and folders. But it doesn't mean, that I avoid this issue.
