### ISSUE TITLE
Terminal emulators have default path set to '/'

### ISSUE THREAD

**Issue by Snakehater** [tvrzna/emptty#104]
Terminal emulators opened after logging in via emptty starts at root directory ('/'), this does not happen to all terminal emulators but most I use. Those that it happens to, does not have this issue when using for example sddm.

Edit: I've used termite and kitty for example.

**Comment by tvrzna** [comment]
Can you provide more info about your setup (distro, `~/.config/emptty` file, `/etc/conf/emptty`, content of your `$PWD` and `$HOME` environment variables, please? Currently I can't find a way, how to reproduce this issue on my virtual machines.

**Comment by Snakehater** [comment]
@tvrzna:
```
(user@pcarch)-[/]
$ echo $PWD 
/
                                                                                 
(user@pcarch)-[/]
$ echo $HOME
/home/user
```
`~/.config/emptty` Doesn't exist, `/etc/conf/emptty` is stock except:
```
DEFAULT_USER=user
```
Distro:
```
$ uname -a
Linux pcarch 6.7.6-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Tue, 27 Feb 2024 19:53:26 +0000 x86_64 GNU/Linux
```
And I use kde plasma on xorg.

**Comment by tvrzna** [comment]
Thank you, I see the problem now: your $PWD is overriden, by default emptty sets it into same value as the $HOME is and then sets is as current dir.

```go
func (s *commonSession) defineEnvironment() {
	s.auth.defineSpecificEnvVariables()

	s.auth.usr().setenv(envHome, s.auth.usr().homedir)
	s.auth.usr().setenv(envPwd, s.auth.usr().homedir)
...
	os.Chdir(s.auth.usr().getenv(envPwd))
```

Do you override somewhere mentioned environment variable? It could be part of some your shell configuration. Or do you use somehow modified version of emptty?
