### ISSUE TITLE
custom logo, i want to ascii , and i only i3wm , and my i3wm is appimage, but i config emptty, it cannot auto i3wm

### ISSUE THREAD

**Issue by newyorkthink** [tvrzna/emptty#105]

**Comment by tvrzna** [comment]
Hello,
you can set your ascii art into `/etc/emptty/motd` and it will override the default ascii. You can also hide issue (the line with your OS identification), see [readme](https://github.com/tvrzna/emptty/blob/master/README.md). However if you want to use autologin, you won't see the ascii for long.
I'm not familiar with AppImage, however I hope it could work as standard WM. Please see [Samples - Custom Sessions](https://github.com/tvrzna/emptty/blob/master/SAMPLES.md#custom-sessions). If you want to use autologin, make sure, that attribute `Name` is same as your value of `AUTOLOGIN_SESSION` in `/etc/emptty/conf`.
