### ISSUE TITLE
Not issue but question 

### ISSUE THREAD

**Issue by ripplingsnake** [tvrzna/emptty#106]
Hello I have been trying to get my system to start a wayland session on tty3 and a game scope session on tty4 , and for the pc to boot directly into the game scope session is this possible with this program? That I can use it to load sessions into 2 tyys so I can freely switch between the two

**Comment by tvrzna** [comment]
Hello,
yes, you can do it. However there is a but - it depends on your distro, how well it works. With Arch Linux I was able to achieve that by running standard service and second instance by running as root `emptty -d -t 4`. With Void Linux I had to create second service (also needed to add `-t 4` to determinate different tty). I've tried that with two Wayland sessions and even two Xorg sessions.
So please, be aware it could be little bit buggy and it requires additional knowledge of emptty params (mainly `-d` for daemon and `-t 4` for running on TTY4 + running it as root, if possible). Also be sure you have no getty running on your selected TTYs.

**Comment by ripplingsnake** [comment]
Thank you I will give it a go I am on manjaro atm

**Comment by ripplingsnake** [comment]
Sorry just to be clear I can just make two different conf/service files with the different tty and sessions and it should run both ? Or can I have them in the same service file  thanks for your help

**Comment by tvrzna** [comment]
`/etc/emptty/conf` is always same for every instance of emptty. However you can override it with arguments. If you want to start second instance as service, you have to duplicate your `/usr/lib/systemd/system/emptty.service` and change
```
ExecStart=/usr/bin/emptty -d
Restart=always
TTYPath=/dev/tty${TTY_NUMBER}
```

into

```
ExecStart=/usr/bin/emptty -d -t [YOUR_TTY_NUMBER]
Restart=always
TTYPath=/dev/tty[YOUR_TTY_NUMBER]
```

**Comment by ripplingsnake** [comment]
Great thanks !

**Comment by ripplingsnake** [comment]
I have it set up but having issues starting a session 
Fork/exec/lib/plasma-dbus-run-session-if-needed:operation not permitted

**Comment by tvrzna** [comment]
Have you tried different desktop environment (just to make sure this way works)?
Also please show me your `/etc/emptty/conf` and eventually your service files for emptty.
