### ISSUE TITLE
Update github.com/msteinert/pam to v2

### ISSUE THREAD

**Issue by supertassu** [tvrzna/emptty#107]
Hi, there's a new major version [`v2`](https://github.com/msteinert/pam/releases/tag/v2.0.0) of the https://github.com/msteinert/pam library used for PAM authentication. Please consider updating to it.

**Comment by tvrzna** [comment]
Hello, I assume, that it's related to the fact of not using thread unsafe finalizer and call `transaction.End()` on ownself. Or is there any other reason since PAM itself is dynamically linked?
I'll check changelogs and I'll try to update the library.

**Comment by tvrzna** [comment]
The update of library led to the dropping of support of older (< 1.20) Golang, which I initially wanted to avoid. However time goes forward and older versions of Golang are no longer supported more than 9 months now. At least it let me to remove usage of deprecated methods and directives.

**Comment by tvrzna** [comment]
Not yet, no one reported any issue with older version of library, so I don't consider it as critical.

**Comment by supertassu** [comment]
Ok. A new release would be helpful since I need to update `emptty` in Debian so that I can update the golang-github-msteinert-pam Debian package to v2. Packaging a full release would be nicer but I can also just pull the last few commits from master to the package for now until there's a new tagged release.

**Comment by tvrzna** [comment]
Well, then it is a different story. I'll release `emptty` as v0.12.1.
