### ISSUE TITLE
Arguments from desktop entry are broken up

### ISSUE THREAD

**Issue by Vladimir-csp** [tvrzna/emptty#109]
Hi!
Testing [uwsm](https://github.com/Vladimir-csp/uwsm) integration via a desktop entry, I have this line in `/usr/share/wayland-sessions/sway-uwsm.desktop`:
```
Exec=uwsm start -N Sway -C "An i3-compatible Wayland compositor" sway
```
It fails with `"i3-compatible" is not in PATH!`, which means that `"An i3-compatible Wayland compositor"` argument was broken up.

**Comment by Vladimir-csp** [comment]
```
    ├─session-147.scope
    │ ├─1567388 /usr/bin/emptty --daemon --tty tty8 --config /etc/emptty/conf-tty8
    │ ├─1567437 /usr/bin/python3 /usr/bin/uwsm start -N Sway -C "\"An_i3-compatible_Wayland_compositor\"" sway
    │ └─1567451 systemctl --user start --wait wayland-wm@sway.service
```
[Quote handling](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html) seems to be missing.

**Comment by tvrzna** [comment]
Hi,
you are right, there is very basic way for handling of Exec and it was simple split by space, which is insufficient for given example. Please, review changeset.

**Comment by Vladimir-csp** [comment]
It won't cover the whole spec, but at least simple quoted arguments would work, which would **probably** be sufficient for most `wayland-sessions` cases.

**Comment by tvrzna** [comment]
The specifications are meant for desktop applications, for DEs/WMs it's overkill.
