### ISSUE TITLE
Add an option to change logging method.

### ISSUE THREAD

**Issue by crocket** [tvrzna/emptty#11]
It always logs to /var/log/emptty. I want to configure logging method.

* Disabling logging
* Letting logrotate take care of log rotation.

**Comment by tvrzna** [comment]
Seems good to me to provide an option how to work with logs (current/appending/disabled). But I don't think it is necessary to change the path of logs since it is common location.

**Comment by crocket** [comment]
I think it's a good idea to document that standard output of a window manager is logged in `/var/log/emptty`. `/var/log/emptty` is not mentioned anywhere.
