### ISSUE TITLE
dbus-launch is probably not needed in systemd environment

### ISSUE THREAD

**Issue by Vladimir-csp** [tvrzna/emptty#112]
I do not have `dbus-launch` in my system (part of `dbus-x11` package which is not installed).
From emptty log:
```
2024/06/08 12:06:10 Starting dbus-launch
2024/06/08 12:06:10 Could not find command 'dbus-launch' on PATH
2024/06/08 12:06:10 No output from dbus-launch
```
Dumping env via `~/.config/emptty` script shows that it already contains `DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus`, which was probably set by systemd-related pam modules.

Perhaps it would be prudent to not even try to run `dbus-launch` if this var is already set.

**Comment by tvrzna** [comment]
It should not start, if `ALWAYS_DBUS_LAUNCH` is not set to `true` and by default it is set to `false`. So first step is to fix the bug that ignores config and second is to check a value of `DBUS_SESSION_BUS_ADDRESS` env.
