### ISSUE TITLE
About PATH again

### ISSUE THREAD

**Issue by Vladimir-csp** [tvrzna/emptty#113]
#45 was reported as fixed, but I'm seeing PATH being overridden (as seen by dumping env in `~/.config/emptty` script)
Default path that should come via pam:
```
/etc/login.defs:ENV_PATH        PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```
emptty runs script with:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
```
which seems to be coming from root.

When logging via agetty to login shell (bash), it receives proper default PATH (as probed by dumping it at the very beginning of `/etc/profile`, before any modifications are made)

**Comment by Vladimir-csp** [comment]
> The mismatch could be caused by the fact, that emptty doesn't source any .profile scripts since there is no default start of login shell, which performs this kind of redefinitions.

No, in case of logging in with agetty I probed `PATH` before `/etc/profile` messed with it. It matched the one from `login.defs`. 
I forgot that agetty just launches `login` which really handles everything, including setting initial `PATH`. So it would be more correct to compare behavior with `login` not `agetty`.

**Comment by tvrzna** [comment]
Current lifecycle of `PATH` variable is quite simple in emptty. If is defined after PAM authentization, it's used. If `PATH` is undefined, then it tooks `PATH` from root - which is common, it won't even be working without any `PATH`. If you `PATH` is not defined after PAM and should be, you have to check configuration in `/etc/pam.d/`.
Without sourcing profile scripts there is no other way to set it.

**Comment by Vladimir-csp** [comment]
> Without sourcing profile scripts there is no other way to set it.

`login` still sets `PATH`, from values of `ENV_PATH` or `ENV_SUPATH` in `login.defs`. According to manpages, many such actions moved to pam, but judging from my experiments, `PATH` is still handled directly by `login`.

**Comment by tvrzna** [comment]
As I described `PATH` lifecycle in emptty, there is no call of `login`.

**Comment by Vladimir-csp** [comment]
I meant that the solution could be to mimic behavior of `login`.

**Comment by tvrzna** [comment]
Sadly reading `login.defs` is not enough to mimic the behaviour of `login`. There are [hardcoded default values](https://github.com/util-linux/util-linux/blob/e9977b8c120c07ded70dfa29a67934004b4d692d/include/pathnames.h#L22-L26) and as I checked few distros, they sometimes rely on the defaults (e.g. Alpine; `login.defs` is almost empty and it also uses [busybox](https://git.busybox.net/busybox/tree/include/libbb.h#n2305)). And I can't find `-devel` package, that would provide these defaults.
This is the kind of situation, why emptty does not support any sourcing of `.profile` scripts.
