### ISSUE TITLE
Automatic selection when only one choice

### ISSUE THREAD

**Issue by fgallaire** [tvrzna/emptty#119]
If there is only one choice of graphical session, it should be possible to not have to validate this choice when login.

**Comment by tvrzna** [comment]
Hello,
this option is available only in case of usage of `.config/emptty` file with `Selection=auto`. Thank you for the suggestion, this is missing.

**Comment by tvrzna** [comment]
If `AUTO_SELECTION` in `/etc/emptty/conf` is set to `true`, it will use the only choice, that is available.
