### ISSUE TITLE
Black screen after login Ubuntu 24.04

### ISSUE THREAD

**Issue by BuiHoangTu** [tvrzna/emptty#122]
I want to try emptty on my laptop with Ubuntu 24.04. I only installed emptty, systemctl enable emptty@tty5 and reboot. After reboot:

- Emptty enabled on tty5
- Emptty does show up after reboot
- Emptty does authenticate users
- Black screen after choose Ubuntu with Xorg 

Here is some log and its status 
![mZfu6K33](https://github.com/user-attachments/assets/c221be37-9ac7-44a6-9d9e-56be46c3265c)

I also tried installing emptty on linux mint 22 with the above steps and it worked normally.

**Comment by tvrzna** [comment]
Please set `SESSION_ERROR_LOGGING` to `appending` in your `/etc/emptty/conf` and then post your log from `/var/log/emptty/session-errors.5.log`. It will tell us more about the problem.

**Comment by BuiHoangTu** [comment]
![20240804_001256.jpg](https://github.com/user-attachments/assets/d6e4b6c0-6fc9-4241-a7ad-2241a4005b06)

There aren't any logs. I noticed that tt5 stuck with update-notifier autostart. Hope this helps. 
![20240804_001522.jpg](https://github.com/user-attachments/assets/a551d588-cd11-4fad-9c86-3f29a635858a)

**Comment by tvrzna** [comment]
I'm sorry, I haven't noticed you have set in your service to use config file `/etc/emptty/conf-tty5`. Put that option there, please.

**Comment by BuiHoangTu** [comment]
![20240804_012451.jpg](https://github.com/user-attachments/assets/4b1d1ea4-599d-43cc-b70a-c66ff165d0c0)

Still no session errors

**Comment by BuiHoangTu** [comment]
@tvrzna  I found .xsession-errors which may contain why emptty didnt work: 
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting XAUTHORITY=/home/tu/.Xauthority
dbus-update-activation-environment: setting XDG_CURRENT_DESKTOP=ubuntu:GNOME
/etc/X11/Xsession.d/30x11-common_xresources: line 16: has_option: command not found
/etc/X11/Xsession.d/75dbus_dbus-launch: line 9: has_option: command not found
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
/etc/X11/Xsession.d/90x11-common_ssh-agent: line 9: has_option: command not found
dbus-update-activation-environment: setting SHELL=/bin/bash
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
dbus-update-activation-environment: setting LANGUAGE=en_US
dbus-update-activation-environment: setting DESKTOP_SESSION=ubuntu
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting PWD=/home/tu
dbus-update-activation-environment: setting XDG_SESSION_DESKTOP=ubuntu
dbus-update-activation-environment: setting LOGNAME=tu
dbus-update-activation-environment: setting XDG_SESSION_TYPE=x11
dbus-update-activation-environment: setting GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
dbus-update-activation-environment: setting XAUTHORITY=/home/tu/.Xauthority
dbus-update-activation-environment: setting XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/tu
dbus-update-activation-environment: setting GDM_LANG=en_US
dbus-update-activation-environment: setting HOME=/home/tu
dbus-update-activation-environment: setting IM_CONFIG_PHASE=1
dbus-update-activation-environment: setting LANG=en_US.UTF-8
dbus-update-activation-environment: setting XDG_CURRENT_DESKTOP=ubuntu:GNOME
dbus-update-activation-environment: setting XDG_SESSION_CLASS=user
dbus-update-activation-environment: setting USER=tu
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting SHLVL=0
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/1000
dbus-update-activation-environment: setting DEBUGINFOD_URLS=https://debuginfod.ubuntu.com 
dbus-update-activation-environment: setting XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/home/tu/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
dbus-update-activation-environment: setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/texlive/2024/bin/x86_64-linux
dbus-update-activation-environment: setting GDMSESSION=ubuntu
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting _=/usr/bin/dbus-update-activation-environment

**Comment by tvrzna** [comment]
I've tried installation of Ubuntu 24.04 LTS, same as you only installed emptty (on updated system) without issue, so I'm unable to replicate the problem to see, how it could be handled. Did it work for you with default `gdm`? Also, if possible, please try to log into different DM/WM (ideally something lightweight as lxde/lxqt/openbox).

**Comment by BuiHoangTu** [comment]
Hi @tvrzna 

After trying emptty on VM, I found out that it worked fine with default config. But if I add .config/emptty, it only displays black screen after choosing Xorg. 
![Screenshot from 2024-08-16 12-35-56](https://github.com/user-attachments/assets/d7e7d759-8bca-4f45-93ee-828ab6e66b53)

Can you look at it again ? Thank you.

**Comment by tvrzna** [comment]
Hello @BuiHoangTu 
try to replace `exec dbus-launch $@` by `exec $@`. In my VM there is no dbus-launch available and it could cause problem. Also make sure, that `xrandr` has correct values (e.g. output display, supported resolution), but with Gnome you can remove this line.

**Comment by BuiHoangTu** [comment]
Replacing with `exec $@` did make emptty work. Thanks.

One more question if you dont mind. How can i make Gnome Display started by emptty look like this 
![Screenshot from 2024-08-16 13-44-21](https://github.com/user-attachments/assets/a1a3855a-f54c-4251-96e6-105c8e11f63f)
instead of this 
![Screenshot from 2024-08-16 13-43-28](https://github.com/user-attachments/assets/0c83cda3-cb19-473a-872b-0ddac41e4d44)

gdm or lightdm both start Gnome like the first image.

**Comment by tvrzna** [comment]
There is an issue with `XDG_CURRENT_DESKTOP` in emptty, it takes values as they are set in `*.desktop` files with semicolons, however Gnome expects colons. You can try to clone latest commit and build emptty yourself or you can add `export XDG_CURRENT_DESKTOP=ubuntu:GNOME` before `exec $@` in your `.config/emptty` file as temporal workaround. But be awere this simple workaround could cause issues with different desktop environments (you can improve it with some condition).

**Comment by BuiHoangTu** [comment]
thanks, everything works now

**Comment by BuiHoangTu** [comment]
thanks, everything works now. I replace `;` in `XDG_CURRENT_DESKTOP` with `:`. Is there anyway to do it with every users or I need to add it manually.

**Comment by tvrzna** [comment]
No, there is no global workaround available except to build `emptty` by yourself.

**Comment by BuiHoangTu** [comment]
Okay, thank you.
