### ISSUE TITLE
Screen locker 

### ISSUE THREAD

**Issue by BuiHoangTu** [tvrzna/emptty#123]
Most DMs have their own version of screen locker. I sometimes switch desktop environment for fun and using emptty means I can't simply lock my screen with the same shortcut (x11 vs wayland locker). Do you plan to add this feature.

**Comment by wesker-albert** [comment]
I'm using `emptty` with a locker. Specifically using `xss-lock` to register `xsecurelock` as my locker. This allows me to just use the command `loginctl locksession` to lock my session.

My understanding is `xss-lock` can be used in conjunction with other lockers, to the same effect.

**Comment by BuiHoangTu** [comment]
> I'm using `emptty` with a locker. Specifically using `xss-lock` to register `xsecurelock` as my locker. This allows me to just use the command `loginctl lock-session` to lock my session.
> 
> My understanding is `xss-lock` can be used in conjunction with other lockers, to the same effect.

I actually use i3lock but my friends told me they are not secure in wayland session. Do you know any solution for both environments ?
