### ISSUE TITLE
Allow passing xorg server arguments.

### ISSUE THREAD

**Issue by crocket** [tvrzna/emptty#14]
For example, I want to pass `-logfile /dev/null` or `-logverbose 2` as arguments to xorg server.

I think xorg server arguments can be specified in `/etc/emptty/conf` or each custom session.

Perhaps, I can create a custom session without any xorg log file.

**Comment by tvrzna** [comment]
Sounds great to pass arguments, but I preffer to keep it only in `/etc/emptty/conf`, at least until there is Xorg-rootless implemented.
Just imagine setting the logfile as `User A` into `/home/userB/`.
