### ISSUE TITLE
Allow custom sessions to configure LOGGING

### ISSUE THREAD

**Issue by crocket** [tvrzna/emptty#15]
For example, I want to enter a session with logging and another session without logging.

This is an easy way to turn logging on and off.

**Comment by tvrzna** [comment]
What is the benefit of this feature? To avoid extensive logging of some WM/DE or to avoid duplication of logs (e.g. starting `i3 (with debug log)`)?

**Comment by crocket** [comment]
I want to have several sessions. For example,

```
i3
i3 with debug log
i3 with xorg log
i3 with debug log and xorg log
sway
sway with debug log
...
```

**Comment by tvrzna** [comment]
This is quite an extreme use-case useful maybe just for few developers. I understand the attention to keep logs as clean as possible, but I don't see the usability for more than 1% of users. Especially when it could be handled by cleaning logs on start of WM/DE.

**Comment by crocket** [comment]
What do you mean by cleaning logs?

**Comment by tvrzna** [comment]
To remove unnecessary log files on each start (e.g. in `~/.profile`, `~/.config/emptty`, etc.).

I don't like the fact, that it would allow to a single user (e.g. without `wheel` or `sudo` access at all) to disable logs of `emptty`.

**Comment by crocket** [comment]
If my mom shares my computer with me by having her own account on my computer, it can be awkward for her to set LOGGING to default if I configured logrotate.

However, session-level control over logging makes things convenient if I want to not log anything at all most of the time.
What if I turned off logging and my mom wanted to turn on logging without root access or without me?

**Comment by tvrzna** [comment]
I don't see the reason, why non-root user should have the permission to define logging of application.
This log file has the meaning to provide help in solving problems, not to expose user activity.

All I can imagine is to allow in configuration to disable WM/DE/Xorg logging into `emptty` log file to prevent showing some kind of sensitive data. This is thing, that could be part of custom session config and application config.

**Comment by crocket** [comment]
Rootless xorg already allows users to define its own logging. By default, it logs in `~/.local/share/xorg/Xorg.0.log`. I can set the logfile path with `-logfile`. I can even disable logging with `-logfile /dev/null`.

Perhaps, emptty could also log in `~/.local` or some other user directory.

**Comment by tvrzna** [comment]
Do not forget, that display manager is not an example of user-level service. I think you are mixing the context of `emptty`, it is not behind getty, it behaves as getty.

**Comment by crocket** [comment]
I think I found a better way to control log. Closing this issue to create another issue.
