### ISSUE TITLE
Make it possible to define path to log file in /etc/emptty/conf

### ISSUE THREAD

**Issue by crocket** [tvrzna/emptty#16]
I suggest something like

/etc/emptty/conf

```
LOGGING-FILE=/path/to/log/file
```

This way, you can control where it is logged. You may also write log on a tmpfs mount where you don't have to worry about wearing storage devices.

**Comment by tvrzna** [comment]
I think it should also allow to enable/disable Xorg/DE/WM logging into that file since it could contain information, that are simply not required.

**Comment by crocket** [comment]
Can you tell me details? I can't imagine what you are talking about.

**Comment by tvrzna** [comment]
In current emptty log file are Xorg and WM/DE logs, which contains e.g. GTK issues or worse, console output of each application started in WM/DE.

**Comment by crocket** [comment]
Are you saying that emptty logs output from xorg, WM, DE, and all GUI programs into /var/log/emptty?

**Comment by tvrzna** [comment]
Yes, it logs standard & error outputs Xorg and WM/DE and I thought you are aware of that. And that's the reason I was talking about it. Sadly it is day zero issue.

**Comment by crocket** [comment]
How do you want to create more control over logging?

**Comment by tvrzna** [comment]
I was thinking about enable/disable flag in config, but now I think there is no valid point to even keep this kind of logs in emptty logs.

**Comment by crocket** [comment]
Not sure that you want to disable them entirely.
But, custom sessions will be able to redirect xorg log with `-logfile`, and custom sessions can already redirect output from DE and WM.

**Comment by crocket** [comment]
Can this issue be considered closed?
