### ISSUE TITLE
OpenRC doesn't work on Gentoo

### ISSUE THREAD

**Issue by niyumard** [tvrzna/emptty#18]
`zsh: /etc/init.d/emptty: bad interpreter: /usr/bin/openrc-run: no such file or directory`

it's actually on 

```
% which openrc-run
/sbin/openrc-run

```

**Comment by tvrzna** [comment]
Hello, have you compiled by yourself or have you used downloaded version? This kind of error happens, when you use musl version on glibc system and opposite.

**Comment by niyumard** [comment]
I compiled it myself, btw the init file doesn't have enable option, is that meant to be?

**Comment by progandy** [comment]
It seems like your system does note have a merged /usr/bin directory. In that case the makefile of emptty has to take care to adjust all paths to the correct directories. At the moment, /usr/bin is hardcoded everywhere.

**Comment by niyumard** [comment]
I think changing Makefile to detect the correct path for openrc would be nice.
But if you don't think so, it'd be okay if you closed this issue.

**Comment by tvrzna** [comment]
I've checked also Alpine and Artix and I believe it is better to just change script to point to `/sbin/openrc-run` than merge `/usr/bin` directory.

**Comment by niyumard** [comment]
And as for the init script not having enable and disable option?

**Comment by tvrzna** [comment]
Since I'm not enough familiar with OpenRC (and Gentoo), what do you mean with enable/disable option? I thought OpenRC handles that itself and no further configuration is required. But I've tested it only with Artix, I am aware I could be wrong.

**Comment by niyumard** [comment]
Unfortunately I'm no better either, I've only recently switched to Gentoo so I mistakenly thought there must be an enable command. I could successfully add emptty to my default runlevel using:
`rc-update add emptty default`
and I also changed `/etc/conf.d/xdm` to look like this: `DISPLAYMANAGER="emptty"` I used [Gentoo's wiki](https://wiki.gentoo.org/wiki/Display_manager) for help.
Unfortunately I'm still facing TTY login instead of emptty.

**Comment by tvrzna** [comment]
Ok, I am glad, there is no change required.

Does it change active TTY? If so, don't you have this TTY occupied by agetty? By default, it should acquire TTY 7, where should not be agetty running. If you have changed TTY in `/etc/emptty/conf`, you have to disable agetty service for that TTY.

**Comment by niyumard** [comment]
Configuring TTY in /etc/emptty/conf (which did not exist before, even the folder) worked. I didn't switch to the right TTY so there doesn't seem to be any problem with emptty. I guess switching to the right TTY doesn't happen by default, so adding a reminder in emptty's github README would be nice.
Thanks!

**Comment by tvrzna** [comment]
Well, if config file wasn't existing, you have to use `make install-config`.

If you use `which chvt`, what does it return, please? If it is not `/usr/bin/chvt`, then there is another Gentoo related bug in `emptty`.

**Comment by niyumard** [comment]
> Well, if config file wasn't existing, you have to use `make install-config`.
> 
> If you use `which chvt`, what does it return, please? If it is not `/usr/bin/chvt`, then there is another Gentoo related bug in `emptty`.

I was under the assumption that `make install-all` is going to install config files too. Pardon me for not reading more carefully. `chvt` is correctly placed in `/usr/bin/chvt `too. It works like a charm now.

Thanks.
