### ISSUE TITLE
Problem with bspwm

### ISSUE THREAD

**Issue by as3ii** [tvrzna/emptty#2]
I've noticed that by default emptty fail starting bspwm. This is the emptty log:
```
2020/06/26 16:29:33 Authenticate OK
2020/06/26 16:29:35 Defined Environment
2020/06/26 16:29:35 Created XDG folder
2020/06/26 16:29:35 Defined uid
2020/06/26 16:29:35 Defined gid
2020/06/26 16:29:35 Defined gids
2020/06/26 16:29:35 Defined Xorg environment
2020/06/26 16:29:35 Created xauthority file
2020/06/26 16:29:35 Generated mcookie
2020/06/26 16:29:35 Generated xauthority
2020/06/26 16:29:35 Starting Xorg
2020/06/26 16:29:35 Started Xorg
2020/06/26 16:29:35 Starting dbus-launch bspwm
The server closed the connection: socket, pipe or stream error.
2020/06/26 16:29:35 dbus-launch bspwm finished
2020/06/26 16:29:35 Interrupted Xorg
2020/06/26 16:29:35 Cleaned up xauthority
```

with i3 everything work. Other DM like lightDM start successfully bspwm

**Comment by as3ii** [comment]
after some attempts, I don't know how, it started

**Comment by as3ii** [comment]
after some attempts, I don't know how, it started

**Comment by tvrzna** [comment]
It's probably related to the dbus-launch. If it appears again, let me, please, know, I would try it too.

**Comment by as3ii** [comment]
@tvrzna I've tried to disable `dbus-launch`, but nothing changed, bspwm wont start
```2020/06/26 20:27:24 Authenticate OK
2020/06/26 20:27:25 Defined Environment
2020/06/26 20:27:25 Created XDG folder
2020/06/26 20:27:25 Defined uid
2020/06/26 20:27:25 Defined gid
2020/06/26 20:27:25 Defined gids
2020/06/26 20:27:25 Defined Xorg environment
2020/06/26 20:27:25 Created xauthority file
2020/06/26 20:27:25 Generated mcookie
2020/06/26 20:27:25 Generated xauthority
2020/06/26 20:27:25 Starting Xorg
2020/06/26 20:27:25 Started Xorg
2020/06/26 20:27:25 Starting bspwm
The server closed the connection: socket, pipe or stream error.
2020/06/26 20:27:25 bspwm finished
2020/06/26 20:27:25 Interrupted Xorg
2020/06/26 20:27:25 Cleaned up xauthority
```

**Comment by tvrzna** [comment]
I've tried to install bspwm and with dbus-launch I've got blank screen (may be caused by not prepared configs), without dbus-launch I've got exact same error message, which seems to be connected to XCB.
I'm sorry, this bug requires more time to investigate and to understand, how to handle it.

**Comment by as3ii** [comment]
> I've tried to install bspwm and with dbus-launch I've got blank screen (may be caused by not prepared configs)

bspwm require a config file and a configured hotkey daemon

**Comment by tvrzna** [comment]
Could you, please, try to pull and build after latest commits? I've tried that, but with same blank screen result. With lightDM it started (or at least I've seen mouse cursor), however you've mentioned, that somehow it started once with emptty.
Let me know, if something has changed. Until then I still consider it as open bug.

**Comment by as3ii** [comment]
with the last changes, bspwm start correctly
