### ISSUE TITLE
"Permission denied" without being able to enter password

### ISSUE THREAD

**Issue by gwerbin** [tvrzna/emptty#20]
Hi! I just installed Emptty with
```bash
sudo make install install-pam install-config install-manual install-systemd 
```
And I started it with `sudo systemctl start emptty`.

However, I get the output "Error: Permission Denied" when I enter my username. I don't see any helpful log output other than "Permission Denied".

Is this a problem with PAM? How can I fix this?

I am using Debian Bullseye, and the latest commit from Emptty master.

**Comment by gwerbin** [comment]
![Login screen with error message](https://user-images.githubusercontent.com/5758789/97765323-072c2300-1ae8-11eb-9f2c-908f781a8c6e.jpeg)

**Comment by tvrzna** [comment]
Hello,
excuse my late response, please. I've just installed Debian Bullseye and as I can see, the issue is with PAM configuration for emptty. It will take some time to fix it (to be sure, that it covers all distros).

As quickfix, if you have installed lightdm, you can use:
```
# rm /etc/pam.d/emptty
# cp /etc/pam.d/lightdm /etc/pam.d/emptty
```

**Comment by tvrzna** [comment]
New `make install-pam-debian` option is available now. There is new distro-specific pam module, I'm not entirely satisfied with current module behavior, but it works.

**Comment by gwerbin** [comment]
Thanks, it works!

What is unsatisfying about the behavior? Can I help somehow?

**Comment by tvrzna** [comment]
Expected behavior is to close session after user being logged out, however `loginctl` shows the session as active.
