### ISSUE TITLE
Dynamic motd

### ISSUE THREAD

**Issue by MDingas** [tvrzna/emptty#22]
It would be neat if the motd could be sourced as something that is generated dynamically, as opposed to a static file.

Perhaps a file like /etc/motd-gen that would be executable, and its output would be printed as the motd? So, for example:

```
#!/bin/bash

fortune | cowsay
```

**Comment by tvrzna** [comment]
Hello,
I was thinking about this feature some time ago and I wasn't sure, if it wouldn't add potential security issue. I can imagine the situation, when this script has wrong write permissions and it executes something dangerous as root (e.g. `rm -rf --no-preserve-root`).

I am still not 100% sure about the security, but I agree this would be really nice feature.

**Comment by MDingas** [comment]
Understandable. In one way you could assume that the script is safe because whoever enabled the emptty service did so with sudo permissions. I guess it could be possible to temporarily lower your permissions to an "emptty" user to execute the script and redirect any errors - including lack of proper permissions - to the log file.

**Comment by tvrzna** [comment]
You are right, if somebody has the permission to install service, there should not be an issue with trust.
Temporarily lowered permissions would be the best way in matter of security, however it could be quite annoying to set up that.

I think an user could be trusted. Just in case, there will be `make install-motd-gen` option, that creates default `/etc/emptty/motd-gen.sh` with correct permissions (744).
