### ISSUE TITLE
Configuration file is marked executable

### ISSUE THREAD

**Issue by MDingas** [tvrzna/emptty#23]
Seems rather minor, but i'm getting the following warning in journalctl:

Nov 13 19:41:04 systemd[1]: Configuration file /usr/lib/systemd/system/emptty.service is marked executable. Please remove executable permission bits. Proceeding >

Potential security flaw with easy fix

**Comment by tvrzna** [comment]
Thank you for the report, another issue was the executable default config file (which was relevant before daemon mode was introduced and emptty was dependent on agetty)
