### ISSUE TITLE
No login sessions reported by `w` or `who` when using `emptty` as display manager

### ISSUE THREAD

**Issue by agherzan** [tvrzna/emptty#24]
I'm on ubuntu 20.04 and after switching from `lightdm` to `emptty`, some applications started to fail. It boils down to the fact that the system doesn't report any currently logged in users. Both `w` and `who` doesn't return anything.

For this to be fixed we need utmp audit.

**Comment by tvrzna** [comment]
Hello,
I am affraid it will take some time to learn to understand and to make utmp audit working. I'll try to do it as soon as possible.

**Comment by agherzan** [comment]
Take your time. Here's an implementation in C (for reference). https://github.com/nullgemm/ly/pull/133

**Comment by tvrzna** [comment]
I've tried to rewrite the functionality for putting UTMP entry, as usual it ended with CGo. With Debian it looks ok with Xorg, but on Void Linux it doesn't look reliable for Xorg (and not working with Wayland). I've tried also utmpx (an inspiration from agetty), however it was unreliable on both distros, so please, try this current version.

I think it requires more time to understand UTMP correctly.

**Comment by agherzan** [comment]
Sadly it doesn't work on ubuntu 20.04.

**Comment by tvrzna** [comment]
I have finally found out, what was wrong. I believe it should work now.

**Comment by agherzan** [comment]
Works great! Nicely done.
