### ISSUE TITLE
Lauch xinitrc with default window manager

### ISSUE THREAD

**Issue by MDingas** [tvrzna/emptty#27]
I'm unsure if the following configuration is possible:

I want to be prompted for my username and password, but skip the manual selection of a window manager and have a default one be passed as an argument to xinitrc. 

If i enable the XINITRC_LAUNCH option, i still get manually prompted for a wm. I guess I could have a script in .config/emptty that calls ~/.xinitrc i3 for example, but that seems like the incorrect way since XINITRC_LAUNCH is an option. Am I missing a better way?

**Comment by tvrzna** [comment]
`~/.config/emptty` could be used not only as a script, but also as config. As it is mentioned in [SAMPLES.md](https://github.com/tvrzna/emptty/blob/master/SAMPLES.md#configemptty-or-emptty-as-config), you can set content of your `~/.config/emptty` to
```
command=/usr/bin/i3
```

With this config and `XINITRC_LAUNCH=true` it should start `~/.xinitrc /usr/bin/i3`.

I am aware it's quite unintuitive.
