### ISSUE TITLE
Executing a script on login/logout.

### ISSUE THREAD

**Issue by b4skyx** [tvrzna/emptty#29]
Is there a way to execute a script as root on login/logout? 

I have a specific usecase which I was wondering if it were possible with emptty.
I wanted to run optimus manager but ran into [this](https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#my-display-manager-is-not-sddm-lightdm-nor-sddm) issue, where I had to run a couple of scripts on login/logout as a workaround.

**Comment by tvrzna** [comment]
Currently there is no such functionality. Maybe dynamic motd could handle start script as root before login, but nothing similar on logout.

**Comment by b4skyx** [comment]
Ah I see. Consider adding it as a functionality in the future releases. For the workaround, I'm just executing a logout script as root xD.
Love the project!
