### ISSUE TITLE
Is it possible to make it working with gnome keyring?

### ISSUE THREAD

**Issue by adlogic** [tvrzna/emptty#31]
Like any other DM out there keyring should auto-start and auto-auth if we have this in pam conf:

auth       optional    pam_gnome_keyring.so
session    optional    pam_gnome_keyring.so auto_start

At least it works for me for lxdm, ly and gdm, but not for emptty. Am I missing something?

**Comment by tvrzna** [comment]
Hi,
I've checked ArchWiki and maybe found the reason. According [GNOME/Keyring](https://wiki.archlinux.org/index.php/GNOME/Keyring#Terminal_applications) there should be started `gnome-keyring-daemon` in `.bash_profile` (if you use `bash`). And this script doesn't run by default, you have to modify `.xinitrc` (if you are using it with Xorg) or your `~/.config/emptty`, if you are using or anything else.

**Comment by adlogic** [comment]
@tvrzna thanks for checking! But unfortunately I cannot make it working. It seems for me that xinitrc does not run as well with emptty, as I have several modifications for xinput there and they are not applied as well... I use bash and Manjaro, with ly (also text based) keyring starts without any modifications (except these 2 strings in pam.d ly), so I actually doubt that this is related to bash starting keyring (after all I do not want to use it in bash, I want to have keyring started on login and that string should do exactly that).

**Comment by tvrzna** [comment]
Check your `/etc/emptty/conf`, if you have option `XINITRC_LAUNCH` set to `true`.

Emptty leaves a lot of responsibilities with configuration to the user. One of them is disabled .xinitrc launch by default.

**Comment by kkga** [comment]
I'm starting gnome-keyring from `~/.config/empty` (which is basically a modified version of my old `xinitrc` file)... it works fine and unlocks automatically on login.
You can see the lines responsible for gnome-keyring in my config here: https://github.com/kkga/dotfiles/blob/master/.config/emptty#L11-L14

**Comment by fabianski7** [comment]
I spent a few hours trying to get this to work, but but without success.
It works out of the box with sddm and also simply running `$ sway` in tty.

maybe some problem on the emptty side? does anyone have it working?
I followed all the tips from archwiki and @kkga 
My /etc/pam.d/sddm and /etc/pam.d/login files are identical

**Comment by tvrzna** [comment]
Does your `/etc/pam.d/emptty` contains following lines?
```
-auth           optional        pam_gnome_keyring.so
-session        optional        pam_gnome_keyring.so auto_start
```

It could be somekind of issue with `emptty`, please provide your `.xinitrc` (if `XINITRC_LAUNCH` is `true`) or your `.config/emptty`. Please, be aware emptty does not follow standard `.bash_profile`, `.profile`, etc scripts, unless they are started manually from `.xinitrc` or `.config/emptty`.

I'm sadly no export for gnome keyring, I hope somebody else could provide another tips to be followed.

**Comment by fabianski7** [comment]
> Does your /etc/pam.d/emptty contains following lines?

yes

> It could be somekind of issue with emptty, please provide your .xinitrc (if XINITRC_LAUNCH is true) or your .config/emptty.

i'm not using XINITRC_LAUNCH. [here my config file ](https://bin.disroot.org/?7f2ce0dd6869f342#Gu8D2Zacyur8WwfAerWQgTkxbYNdaRQsw2uKyicz6N75)

**Comment by tvrzna** [comment]
Then I recommend to add:
```
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK
```
before the exec line. See [archwiki](https://wiki.archlinux.org/title/GNOME/Keyring#xinitrc). If you already tried it without success, I'm afraid I have nothing more to add than [this](https://wiki.gnome.org/Projects/GnomeKeyring/RunningDaemon).
