### ISSUE TITLE
/etc/pam.d/emptty errors in Fedora 33 and AUTOLOGIN=false ignored if fixed

### ISSUE THREAD

**Issue by PreciousPudding** [tvrzna/emptty#32]
I am on Fedora 33 with kernel `5.9.16-200.fc33.x86_64`. 

I ran the following code to build and install:
```
make build
sudo make install-all
sudo make install-config
sudo make install-motd-gen
sudo make install-systemd
sudo systemctl enable emptty
```

I encountered an error similar to that found in #20. After reading #20 and #7 I changed the instances of `system-login` in `/etc/pam.d/emptty` to `system-auth` since that exists in my `/etc/pam.d` ![directory](https://user-images.githubusercontent.com/49357631/103426542-dfa51580-4b7f-11eb-9cec-7a24fbcaa7ba.png) (I apologize if the transparency makes it harder to read). 

With that change, I can not only get into my WM but also autologin. 

However, the issue is that I will **always** autologin no matter if I have `AUTOLOGIN=true` or `false` set in /etc/emtty/conf`. I have not been able to find a solution for this issue yet. 

The folllowing are my files relevant to emptty:

/etc/emptty/conf:
```
# TTY, where emptty will start.
TTY_NUMBER=7

# Enables switching to defined TTY number.
SWITCH_TTY=true

# Enables printing of /etc/issue in daemon mode.
PRINT_ISSUE=true

# Preselected user, if AUTOLOGIN is enabled, this user is logged in.
DEFAULT_USER=krisbalintona

# Enables Autologin, if DEFAULT_USER is defined and part of nopasswdlogin group. Possible values are "true" or "false".
AUTOLOGIN=false

# The default session used, if Autologin is enabled. If session is not found in list of session, it proceeds to manual selection.
AUTOLOGIN_SESSION=awesome

# Default LANG, if user does not have set own in init script.
#LANG=en_US.UTF-8

# Starts desktop with calling "dbus-launch".
DBUS_LAUNCH=true

# Starts Xorg desktop with calling "~/.xinitrc" script, if is true, file exists and selected WM/DE is Xorg session, it overrides DBUS_LAUNCH.
XINITRC_LAUNCH=true

# Prints available WM/DE each on new line instead of printing on single line.
VERTICAL_SELECTION=true

# Defines the way, how is logging handled. Possible values are "default", "appending" or "disabled".
#LOGGING=default

# Arguments passed to Xorg server.
#XORG_ARGS=

# Overrides path of log file
#LOGGING_FILE=/var/log/emptty

# Allows to use /etc/emptty/motd-gen.sh script to generate custom MOTD.
#DYNAMIC_MOTD=false

# Foreground color, available only in daemon mode.
FG_COLOR=LIGHT_WHITE

# Background color, available only in daemon mode.
#BG_COLOR=BLACK
```

/etc/pam.d/emptty:
```
#%PAM-1.0
auth            sufficient      pam_succeed_if.so user ingroup nopasswdlogin
auth            include         system-auth
-auth           optional        pam_gnome_keyring.so
account         include         system-auth
password        include         system-auth
session         include         system-auth
-session        optional        pam_gnome_keyring.so auto_start
```

~/.config/emptty:
```
Name=AwesomeWM
Exec=/usr/bin/awesome
Environment=xorg
```

**Comment by tvrzna** [comment]
Hello,
it looks like `system-auth` allows autologin. I'll try to install, inspect and find preferable option, that doesn't cause autologin.
However it takes some time to prepare virtual machine, please be patient.

**Comment by tvrzna** [comment]
I am really sorry, but I'm failing to reproduce the bug with Fedora 33 with `5.9.16-200.fc33.x86_64` kernel.
Please try to replace `system-auth` with `password-auth`, which doesn't support fingerprint reader authentication (if you have any).

Please let me know, if it helps. The PAM module for Fedora (and CentOS I believe) should be available in `emptty` also.

**Comment by PreciousPudding** [comment]
@tvrzna `password-auth` does indeed prevent autologin but then autologin does not work at all event if `AUTOLOGIN=true`.

**Comment by tvrzna** [comment]
Be sure you haven't remove the line `auth            sufficient      pam_succeed_if.so user ingroup nopasswdlogin` in PAM, and be sure you have used `sudo groupadd nopasswdlogin` and `sudo usermod -aG nopasswdlogin krisbalintona`. With this autologin should work, even it's not exactly intuitive.
