### ISSUE TITLE
Feature request: handle the \4 and \6 escape sequences

### ISSUE THREAD

**Issue by gwerbin** [tvrzna/emptty#34]
Agetty is able to parse sequences like `\4{enp4s0}` and `\6{enp4s0}` to obtain the IPv4/IPv6 address on that interface. Would it be possible to add this capability to Emptty as well?

I looked at the Go source, but it doesn't seem like the current `issueVariable` struct is able to handle this kind of thing. I'm not a good enough Go programmer to refactor this. But after the parsing is done, it seems easy to query the interface using [`net.InterfaceByName`](https://golang.org/pkg/net/#InterfaceByName).

The Agetty implementation is here, if it helps:
* https://github.com/karelzak/util-linux/blob/3fb46f5e7bdff350e93ff7301a6abda2ad4e6dec/term-utils/agetty.c#L2827-L2849
* https://github.com/karelzak/util-linux/blob/3fb46f5e7bdff350e93ff7301a6abda2ad4e6dec/term-utils/agetty.c#L2568-L2646

**Comment by tvrzna** [comment]
As you mentioned, the current `issueVariable` handling is really primitive and not able to handle this kind of escape sequences. It needs to be reworked.

**Comment by tvrzna** [comment]
Please, check these commits, if it meets requirements. Be aware it doesn't follow Agetty algorithm.

**Comment by gwerbin** [comment]
It works perfectly, thank you!
