### ISSUE TITLE
Running commands (or executables) after closing the session.

### ISSUE THREAD

**Issue by c0dewriter** [tvrzna/emptty#37]
Hi, 
So I'm using @[Askannz/optimus-manager](https://github.com/Askannz/optimus-manager/) on my home Arch machine. 
And if you look at [this](https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#my-display-manager-is-not-sddm-lightdm-nor-sddm) section in the Wiki, it mentions that the `prime-switch` command must be ran _after_ the X session is closed (as root).
And I think that running commands/scripts/etc is a nice feature to have. For example I may want to:
- Unmount "external" partitions. 
- Stop auxiliary services after I'm done with work (like Tor).
- Close VPN connections.
- Run my top-secret Rust-based backup binary.
 

_BTW: I would have happily contributed myself, but I don't know/like Go :P_
_Love the work you've done so far. Thank you_

**Comment by tvrzna** [comment]
Hello,
as I can see, there is already more people wanting this feature (#29, @b4skyx will be happy too). At first I was kind of against running root script, but it was short sighted.
The only issue I can see is the fact this script will be same for all users (on single machine), but so it is in SDDM and LightDM (according Wiki & config files of optimus-manager).
