### ISSUE TITLE
Don't default to en_US.UTF-8

### ISSUE THREAD

**Issue by gfarrell** [tvrzna/emptty#38]
When trying out emptty I ran into a problem with rofi not launching from within i3. I discovered, by printing `env | sort` from within i3 and also within my shell (whence launching rofi _did_ work) that this was because i3 had `LANG=en_US.UTF-8` set, and this, I realised, was coming from emptty.

For me, in `/etc/locale.conf` the locale is defined, and `en_US.UTF-8` is not available on my system, so is it possible for emptty to load only locally defined locales, not en_US.UTF-8 by default?

**Comment by tvrzna** [comment]
You can set your `LANG` in `/etc/emptty/conf` or `~/.emptty`/`~/.config/emptty`, if you use that. However you are right, it should not assume `en_US.UTF-8` as default. If `LANG` environmental variable is available, it is used as default, but if it is not defined, it uses `en_US.UTF-8` as fallback.

**Comment by gfarrell** [comment]
Yes, I fixed the issue by setting it manually, I was more talking about the
default behaviour in the case in which the locale is set on the machine --
emptty should then use the specified locale rather than having to be
explicitly configured.

--
*Gideon Farrell*
*Co-founder / CTO*
www.converge.io
