### ISSUE TITLE
Add option to auto-enable numlock

### ISSUE THREAD

**Issue by TJ-Hooker15** [tvrzna/emptty#40]
I think it'd be nice if there was an option (e.g. a field in /etc/emptty/conf) to auto-enable numlock in emptty. This would make it more convenient to enter alph-numeric passwords at login.

Admittedly I'm not sure if this request even makes sense in this context, maybe numlock is something that is controlled outside of emptty. But none of the things I've tried to auto-enable numlock on startup have had any effect on the emptty login screen (but work otherwise).

**Comment by TJ-Hooker15** [comment]
Well, I feel a little silly. I had made a script that used setleds to enable numlock on various ttys (similar to the example in the [man page](https://linux.die.net/man/1/setleds)), and had put it in rc.conf. However, the example I had been looking at only set ttys 1 through 6, and emptty was set to use tty7...

So I have numlock working in emptty now, but I still think it'd be nice to have an option for numlock built right into the emptty config. Assuming such a request makes sense in the first place for a program like emptty.

**Comment by tvrzna** [comment]
Hello,
I am sorry for late response and making you feel "a little silly". I agree, it could be handy to have this kind of feature inside of emptty. I'll try to find the way how to code it without using `setleds` (since it does not have to be a part of distro).
