### ISSUE TITLE
XDG_RUNTIME_DIR should be respected if it's already set.

### ISSUE THREAD

**Issue by crocket** [tvrzna/emptty#41]
Right now, emptty just sets XDG_RUNTIME_DIR to `/run/user/uid`.

However, https://github.com/FredrikAleksander/pam_rundir sets XDG_RUNTIME_DIR to `/run/users/uid` and creates it.

Thus, emptty fails. emptty should respect XDG_RUNTIME_DIR passed from pam_rundir.

**Comment by tvrzna** [comment]
You are right, it should respect already defined `XDG_RUNTIME_DIR` and probably it should also respect `XDG_CONFIG_HOME` and `XDG_SEAT`, if these values should be overriden.
