### ISSUE TITLE
Make an entry for artix inits

### ISSUE THREAD

**Issue by Twilighttony** [tvrzna/emptty#43]
Hello, I was wondering if it was possible to make an entry in the make install section to have the init scripts get put into the proper folder in /etc/? I use runit and when I installed using `sudo make install-runit` it put the init script into /etc/sv rather than /etc/runit/sv

**Comment by tvrzna** [comment]
Hello,
new `sudo make install-runit-artix` command is added, it should create service into `/etc/runit/sv` folder. I hope this helps.
