### ISSUE TITLE
How can I populate xsession-errors like lightdm does?

### ISSUE THREAD

**Issue by hellmind** [tvrzna/emptty#46]
How can I do that?
in lightdm there is no need for 2 >&1  on every program I run.
I cant find how some dm do that so I can doit manually
I tried to run xorg like that on argvs and doesnt work
# Arguments passed to Xorg server.
#XORG_ARGS='2>&1 > ~.xsession-errors'

**Comment by tvrzna** [comment]
There is no configuration for that yet. However I am planning to add the possibility to enable logging from Xorg and session (no matter, if Xorg or Wayland). And as I see now, there would be interesting to split it into `stdout` and `stderr` outputs.

I don't have experience with `XORG_ARGS`, but you have commented the line by `#` and the output file is missing `/` (`~/.xsession-errors`).

**Comment by hellmind** [comment]
I commented it because it doesn't work (blocks the startup). 
I will try adding the '/' as you said.

Also I note that isn't work like llightdm, 
Maybe lightdm is doing more things. 
My sound doesn't work correctly, lightdm does some env variable assignation that make pipewire works ok 
Also, my cursor in some apps doesn't show as it should, maybe isn't loading .Xresources. (some qt/gtk theme settings are ignored)

**Comment by tvrzna** [comment]
Yes, emptty does not source `.profile`, `.Xresources` and similar files, you have to source them ownself, e.g. `xrdb -merge ~/.Xresources` in `.xinitrc` or `.config/emptty` (depends on your use case, which one).

**Comment by tvrzna** [comment]
There is maybe one more thing with your issue with logging. `emptty` is being started as root, so `~` is maybe not your home folder, but the root's one.
