### ISSUE TITLE
Update in reference to the user in README.md

### ISSUE THREAD

**Issue by gothgirl68k** [tvrzna/emptty#47]
I love this display manager as it does everything a display manager should do efficiently in my eyes, so thank you so much to @tvrzna especially and all of the other contributors :heart: 

There's an issue under `Logging/appending` in README.md, in which the docs refer to the user as 'himself' which isn't accurate to the more diverse user-base of the application. I think this should be 'themselves' instead to also represent women and other people using not only a masculine pronoun.

> appending
> 
> This option provides functionality that logs everything into /var/log/emptty and does not handle log rotation by itself. It leaves the option for user to handle it **himself** (e.g. with logrotate).

Apologies for bringing this up as it's only one word and is likely only mistranslation or a typo. Thanks for your time :)

**Comment by tvrzna** [comment]
Hello, I am really glad you like emptty!
I think I am the one, who should apologise. It's really just a mistranslation. Thank you for correction.
