### ISSUE TITLE
/etc/profile is not run

### ISSUE THREAD

**Issue by thenktor** [tvrzna/emptty#52]
Hi,

I'm using emptty on Void Linux and I've noticed that (in contrast to all other display manager that I have tried) `/etc/profile` is not run, even with bash as default shell.
As effect at least the PATH variable is not correct (missing `/usr/local` dirs) and other environment variables from scripts within `/etc/profile.d` are not set, too.

I wonder if this is a bug? Or it's not a bug, it's a feature?

**Comment by thenktor** [comment]
OK, I've found #4 

Setting `XINITRC_LAUNCH=true` and adding this to `.xinitrc` solves this for now:
```bash
if [ -f /etc/profile ]; then
  . /etc/profile
fi
exec dbus-launch $@
```

Problem left: when using another display manager `/etc/profile` is sourced twice now :disappointed:

**Comment by tvrzna** [comment]
Hello,
I'm glad you have found the workaround and I am sorry it annoys you. But there is also different option, how to handle this situation. See [page with Samples](https://github.com/tvrzna/emptty/blob/master/SAMPLES.md#configemptty-or-emptty-as-init-script), where is `~/.config/emptty` file used as init script (as an alternative to `.xinitrc`). This init script is usable also for wayland.

**Comment by thenktor** [comment]
Not annoyed, just not fully satisfied with my solution :wink: I've already tried `~/.config/emptty` as script but then the DE choser was gone. If I get this right I probably need the `Selection=true` variable set. I'll test that, thanks for the hint!

I guess these are quite common problem, maybe it helps to give them a more prominent position in README.md?

**Comment by tvrzna** [comment]
Yes, the `Selection=true` does the trick, I hope it will be the right solution for you.

You are right, it should be mentioned in README.

**Comment by thenktor** [comment]
Thank you, works for me :+1:
