### ISSUE TITLE
Empty /etc/emptty/motd gives unwanted new lines

### ISSUE THREAD

**Issue by ZerdoX-x** [tvrzna/emptty#55]
To reproduce: 
```
#/etc/emptty/conf
PRINT_ISSUE=false
```
run `touch /etc/emptty/motd`

![image](https://user-images.githubusercontent.com/49815452/139517694-371531d7-58c7-4c75-8932-c6967d1470cf.png)

**Comment by tvrzna** [comment]
You're right, this looks bad and it is caused due to incomplete testing of this situation. In this case, it's bug (since any new lines should not be there) and it will be also as config parameter `PRINT_MOTD`, because it should be easier to disable motd.
