### ISSUE TITLE
[Feature] Add DEFAULT_SESSION parameter

### ISSUE THREAD

**Issue by s3rj1k** [tvrzna/emptty#60]
Please consider adding DEFAULT_SESSION parameter, so when specified, emptty would start that session directly (if available) without prompting to choose what to start.

**Comment by tvrzna** [comment]
Hello,
I think this is nice idea. However until it's done, you can try to use [emptty file](https://github.com/tvrzna/emptty/blob/master/SAMPLES.md#configemptty-or-emptty-as-config), which works almost the same way, but is specific for each user.
