### ISSUE TITLE
emptty creates ~/.cache directory as root

### ISSUE THREAD

**Issue by mohan43u** [tvrzna/emptty#62]
https://github.com/tvrzna/emptty/blob/dc7c5300d4527de262c10a0724ec4467bf0f2c85/src/login.go#L77

Seems emptty creates ~/.cache directory as root when setting autologin with max_retry > 0 (which is default). Kindly address this issue.

**Comment by tvrzna** [comment]
Hello, this is just wrong, I'm sorry I haven't noticed that already. Going to fix this ASAP.
