### ISSUE TITLE
Rootless Xorg

### ISSUE THREAD

**Issue by s3rj1k** [tvrzna/emptty#63]
I assume that to run Xorg rootless emptty also needs to be run in daemon mode, according to https://github.com/tvrzna/emptty/blob/master/src/session_xorg.go#L52 ?

Could you please update the docs if I am correct

**Comment by tvrzna** [comment]
Yes, it's true, it runs only in daemon mode (`-keeptty` wouldn't work, if emptty's TTY differs from target TTY).
