### ISSUE TITLE
Seldom set_loginuid errors in journalctl logs

### ISSUE THREAD

**Issue by s3rj1k** [tvrzna/emptty#64]
```
pam_loginuid(emptty:session): set_loginuid failed
pam_loginuid(emptty:session): Error writing /proc/self/loginuid: Operation not permitted
```

Everything works as usual to my knowledge, when this error is happening

**Comment by tvrzna** [comment]
I've tried to reproduce this warning on Debian, Void and Arch, but without any success; `pam_loginuid` is optional and no warning is thrown.

However for OpenSUSE there is different module with `pam_loginuid` set as required (created by PR #33). Which distro are you using, please? If it is OpenSUSE, could you, please try to change to value in `/etc/pam.d/emptty`?

**Comment by s3rj1k** [comment]
@tvrzna I am using Manjaro (Arch), I see this error from time to time, today for example did not see it.

```
-- Boot 31a9925ec58542c1988c4db599fcc0e5 --
Apr 07 13:33:41 s3rj1k-swift1 systemd[1]: Started emptty display manager.
Apr 07 13:33:43 s3rj1k-swift1 emptty[455]: pam_succeed_if(emptty:auth): requirement "user ingroup nopasswdlogin" not met by user "s3rj1k"
Apr 07 13:33:43 s3rj1k-swift1 emptty[455]: pam_systemd_home(emptty:auth): systemd-homed is not available: Unit dbus-org.freedesktop.home1.servic>
Apr 07 13:33:46 s3rj1k-swift1 emptty[455]: gkr-pam: unable to locate daemon control file
Apr 07 13:33:46 s3rj1k-swift1 emptty[455]: gkr-pam: stashed password to try later in open session
Apr 07 13:33:47 s3rj1k-swift1 emptty[455]: pam_loginuid(emptty:session): Error writing /proc/self/loginuid: Operation not permitted
Apr 07 13:33:47 s3rj1k-swift1 emptty[455]: pam_loginuid(emptty:session): set_loginuid failed
Apr 07 13:33:47 s3rj1k-swift1 emptty[455]: pam_unix(emptty:session): session opened for user s3rj1k(uid=1000) by (uid=0)
Apr 07 13:33:48 s3rj1k-swift1 emptty[455]: pam_env(emptty:session): deprecated reading of user environment enabled
Apr 07 13:33:48 s3rj1k-swift1 emptty[455]: gkr-pam: gnome-keyring-daemon started properly and unlocked keyring
Apr 07 22:22:08 s3rj1k-swift1 systemd[1]: Stopping emptty display manager...
Apr 07 22:22:09 s3rj1k-swift1 systemd[1]: emptty.service: Deactivated successfully.
Apr 07 22:22:09 s3rj1k-swift1 systemd[1]: Stopped emptty display manager.
Apr 07 22:22:09 s3rj1k-swift1 systemd[1]: emptty.service: Consumed 4.275s CPU time.
-- Boot 23c7af98e3384ace991591f21335f489 --
Apr 08 09:14:05 s3rj1k-swift1 systemd[1]: Started emptty display manager.
Apr 08 09:14:07 s3rj1k-swift1 emptty[472]: pam_succeed_if(emptty:auth): requirement "user ingroup nopasswdlogin" not met by user "s3rj1k"
Apr 08 09:14:07 s3rj1k-swift1 emptty[472]: pam_systemd_home(emptty:auth): systemd-homed is not available: Unit dbus-org.freedesktop.home1.servic>
Apr 08 09:14:11 s3rj1k-swift1 emptty[472]: gkr-pam: unable to locate daemon control file
Apr 08 09:14:11 s3rj1k-swift1 emptty[472]: gkr-pam: stashed password to try later in open session
Apr 08 09:14:12 s3rj1k-swift1 emptty[472]: pam_unix(emptty:session): session opened for user s3rj1k(uid=1000) by (uid=0)
Apr 08 09:14:12 s3rj1k-swift1 emptty[472]: pam_env(emptty:session): deprecated reading of user environment enabled
Apr 08 09:14:12 s3rj1k-swift1 emptty[472]: gkr-pam: gnome-keyring-daemon started properly and unlocked keyring
```

**Comment by tvrzna** [comment]
Still trying to figure out why is this happening. At this moment I can say, it's not related to Rootless Xorg and it's not related to [utils.go:doAsUser()](https://github.com/tvrzna/emptty/blob/master/src/utils.go#L262-L270). The strange thing is it happens just sometimes.
I have to review PAM library and mainly its usage in emptty, if there is nothing wrong from my side.

**Comment by s3rj1k** [comment]
Do you need some PAM configs from my system?

**Comment by tvrzna** [comment]
No, thank you. Sometimes it happens to me too, but for last hour without success.

**Comment by tvrzna** [comment]
Looks like the issue is caused by golang behaviour, which could make running of PAM open session in different than main thread. If you are able to build from `master` branch, can you please try it. During testing it helped, but I'd prefer to have it confirmed.

**Comment by s3rj1k** [comment]
@tvrzna added comment https://github.com/tvrzna/emptty/commit/4640ee382c18c3a46403800e784a9c3327a6cae0#r70982193

will try to use master and report back

**Comment by s3rj1k** [comment]
@tvrzna looks good from my side, please do a tagged release

**Comment by tvrzna** [comment]
Thank you for the retest. I don't think this requires hotfix release, this bug was presented since first release. However a new release is planned for the end of this month.
