### ISSUE TITLE
session type not set properly

### ISSUE THREAD

**Issue by peterwu** [tvrzna/emptty#66]
emptty doesn't set the session type to **x11** after logging into an X session. This leads to the incorrect IdleHint for logind.

```
$ loginctl show-session $XDG_SESSION_ID
...
Type=tty
...
```

**Comment by tvrzna** [comment]
Session Type does not change IdleHint itself, however `Type=tty` does not allow to change to value. Please make sure, that you set `IdleHint` after logging into an X session with this fix.
