### ISSUE TITLE
Password: Error: Authentication token manipulation error on gentoo

### ISSUE THREAD

**Issue by crocket** [tvrzna/emptty#7]
Whenever I enter a username, I see `Password: Error: Authentication token manipulation error`.

Version: 0.2.3

**Comment by tvrzna** [comment]
Hello,
do you have correctly installed pam (and does it exist as `/etc/pam.d/emptty`)?
If it is correct, try to set this content instead of standard
```
#%PAM-1.0
auth            sufficient      pam_succeed_if.so user ingroup nopasswdlogin
auth            include         system-local-login
account         include         system-local-login
password        include         system-local-login
session         include         system-local-login
```

Those are just quick first ideas, that I have. I'll try to inspect more, what could happen.

**Comment by crocket** [comment]
The following content for `/etc/pam.d/emtty` doesn't change the outcome.

```
#%PAM-1.0
auth            sufficient      pam_succeed_if.so user ingroup nopasswdlogin
auth            include         system-local-login
account         include         system-local-login
password        include         system-local-login
session         include         system-local-login
```

**Comment by tvrzna** [comment]
To be sure, do `system-local-login` and `system-login` exist in your `/etc/pam.d/`?

This error is surely on pam/authorization side, but the question is, if the issue is caused by [shadow](https://askubuntu.com/questions/57620/getting-an-authentication-token-manipulation-error-when-trying-to-change-my-us), [pam](https://bugs.gentoo.org/738600) itself or by pam configuration of `emptty` for gentoo.

**Comment by crocket** [comment]
```
$ grep -r system-local-login /etc/pam.d
/etc/pam.d/login:auth       include     system-local-login
/etc/pam.d/login:account    include     system-local-login
/etc/pam.d/login:password   include     system-local-login
/etc/pam.d/login:session    include     system-local-login
/etc/pam.d/emptty:auth            include         system-local-login
/etc/pam.d/emptty:account         include         system-local-login
/etc/pam.d/emptty:password        include         system-local-login
/etc/pam.d/emptty:session         include         system-local-login
/etc/pam.d/runuser-l:auth       include system-local-login
/etc/pam.d/runuser-l:account    include system-local-login
/etc/pam.d/runuser-l:password   include system-local-login
/etc/pam.d/runuser-l:session    include system-local-login
```

```
$ grep -r system-login /etc/pam.d
/etc/pam.d/system-remote-login:auth             include         system-login
/etc/pam.d/system-remote-login:account          include         system-login
/etc/pam.d/system-remote-login:password include         system-login
/etc/pam.d/system-remote-login:session          include         system-login
/etc/pam.d/system-local-login:auth              include         system-login
/etc/pam.d/system-local-login:account           include         system-login
/etc/pam.d/system-local-login:password  include         system-login
/etc/pam.d/system-local-login:session           include         system-login
```

**Comment by tvrzna** [comment]
Before I manage to install Gentoo or at least Sabayon, have you tried to check this [thread](https://bugs.gentoo.org/738600#c7) on Gentoo forum related to this error with passwd?

I've already tried another distributions (that I have already installed) and still could not reproduce. I'm not trying to avoid Gentoo, it just takes the time :)

**Comment by crocket** [comment]
I checked /var/log/messages after failing to log in on emptty.

```
emptty[5830]: pam_unix(emptty:auth): conversation failed
emptty[5830]: pam_unix(emptty:auth): auth could not identify password for [guardian]
supervise-daemon[5485]: /usr/bin/emptty, pid 5830, exited with return code 1
supervise-daemon[13294]: Child command line: /usr/bin/emptty -d
```

**Comment by crocket** [comment]
After setting TTY_NUMBER to 6 in /etc/emptty/conf, I could log in on emptty, but emptty logs in to bash instead of showing a list of options for GUI sessions.

**Comment by tvrzna** [comment]
Are you sure, that it was really emptty and not getty? There is no option to log into bash.
If you have changed TTY number, you have to make sure, that there is no getty instance/service running already.

However, according the log and quick search on the internet, try to update `/etc/pam.d/emptty`

```
#%PAM-1.0
auth            sufficient      pam_permit.so
auth            sufficient      pam_succeed_if.so user ingroup nopasswdlogin
auth            include         system-local-login
account         include         system-local-login
password        include         system-local-login
session         include         system-local-login
```

I'm getting closer to have prepared environment, I hope it will provide us quicker and better answers than my wild guessing.

**Comment by crocket** [comment]
`auth            sufficient      pam_permit.so` bypasses security, so pam_permit.so makes it work without password.

**Comment by tvrzna** [comment]
The point was to try to find, what goes wrong and if emptty is able to log into X/Wayland at all.
However I've finally managed to install Gentoo and I'm getting the same error (with pam_permit.so it goes through, as you said - without password).

**Comment by crocket** [comment]
Emptty works on artix linux which is a derivative of arch linux.

**Comment by tvrzna** [comment]
I know, I've already tested in on Artix (with OpenRC), Manjaro & Arch, Void (glibc & musl).

I've just found out, that it has something to do with disabling echo by `stty` before password could be inserted. If this part of code is commented (in `password.go`, lines 13 - 26), it works. But the password is readable.

**Comment by tvrzna** [comment]
Please, checkout the last change. The issue was caused by my ignorance to Gentoo, which does not have linked /bin to /usr/bin (for exec of `stty`) as other distribtution I was using for testing.

**Comment by crocket** [comment]
Why don't you look for the path to stty through `which` or `$PATH` instead?

**Comment by crocket** [comment]
Anyway, the latest commit fixes the issue. But, I encountered another issue that lots of sway keyboard shortcuts don't work when sway is launched on emptty.

**Comment by crocket** [comment]
Closing the issue for now.
