### ISSUE TITLE
request for binary package [AUR]

### ISSUE THREAD

**Issue by ghost** [tvrzna/emptty#75]
Installation requires go language (which is a huge dependency). I know it's a small application. Instantaneous compilation too. But providing a binary alongside is useful.

**Comment by tvrzna** [comment]
Hello,
it would be difficult to maintain different libc and their version for each distro. Even if it would be built by Github Actions.

**Comment by pc00per** [comment]
> Hello, it would be difficult to maintain different libc and their version for each distro. Even if it would be built by Github Actions.

Oh. That's unfortunate. It's there an other economical way btw ?

**Comment by tvrzna** [comment]
The simplest solution is to use standard make process with different distros via docker (as Github Actions provides). Arch Linux was used for testing after push (without binary publishing), but there was a period, when the docker image was not working with latest pacman updates and all build were just failing, even the code was ok.

**Comment by pc00per** [comment]
Or how about supporting global repos ? Flatpak & snap. That would be much easier though.

**Comment by tijko** [comment]
If you'd like I would be up for writing some `PKGBUILD` files for _Archlinux_.

**Comment by tvrzna** [comment]
Feel free to create the AUR bin package.

**Comment by tijko** [comment]
> Feel free to create the AUR bin package.

@tvrzna Are you sure its not already there?

https://aur.archlinux.org/packages/emptty

**Comment by tvrzna** [comment]
Yes, there's also git version, however reporter was asking for emptty's binary package, something like to unpack deb version (which already exists) and repack it for pacman without necessity of building the package on their own.

**Comment by tijko** [comment]
I opened a PR https://github.com/tvrzna/emptty/pull/94

**Comment by tvrzna** [comment]
Thank you, however binary package does not belong to source code repository.

**Comment by tijko** [comment]
I realize that :) I wanted to at least get it out there.  I'm not an Archlinux TU and that's not something that can come about by simply creating an account.

We'd have to get this to a core maintainer or somebody that will vouch to maintain the package (e.g. PKGBUILD, *.zstd, etc);

**Comment by tijko** [comment]
@tvrzna I had time to double back around and dive into this more.

> We'd have to get this to a core maintainer or somebody that will vouch to maintain the package (e.g. PKGBUILD, *.zstd, etc);

I was unclear at the time and this isn't exactly true.

Under the Archlinux forums and AUR I created a couple of accounts and registered so I will be able to put a request through.  It appears to be pretty trivial but I didn't know it at the time.

**Comment by tvrzna** [comment]
I have to appreciate your passion to reach the goal! Of course I'll be glad, if `emptty` could be a package in Arch. If you feel, that you can achieve it, then please go for it. Many people can benefit from it.

**Comment by tijko** [comment]
@tvrzna I'm making the finishing touches to the `PKGBUILD` there are a few details I was going to need to include.

One being the "maintainer" which would be your name and email.

**Comment by tvrzna** [comment]
@tijko isn't meant maintainer of package instead of a developer? However my name and email are reachable from commits - I don't hide them there.

**Comment by tijko** [comment]
@tvrzna coincidentally I just looked not more than 20secs ago...

**Comment by tijko** [comment]
@tvrzna https://aur.archlinux.org/packages/emptty-bin

**Comment by tvrzna** [comment]
@tijko This is a bin version just by its name, isn't it? This is almost as same as Orhun's version, that also requires to be built on user's device.

**Comment by tijko** [comment]
I hadn't decided where to keep the binary at this point but just this morning created an archive of the necessary files (e.g. binary, conf, man).

https://github.com/tijko/emptty-bin this would be a more complete version and more accurate to get an idea of where things are.
