### ISSUE TITLE
How to escape to default tty login shell?

### ISSUE THREAD

**Issue by Tinkerbells** [tvrzna/emptty#77]
I'm switching from arch to void and testing a lot of logins managers such as lightdm, sddm. And when I have a trouble with them I can easily press alt+ctrl+f2 to switch back to default tty login shell and change config files. How to do that with emptty?

**Comment by tvrzna** [comment]
There is nothing to block switch to another TTY. In fact I used that today on Arch and Void. In both cases on real machines, not a virtual one.
