### ISSUE TITLE
No desktop found - void - xorg

### ISSUE THREAD

**Issue by BeefcakeTheMighty** [tvrzna/emptty#78]
I have XINITRC_LAUNCH=true and the .xinitrc file in my home directory is executable but I'm still getting a "No Desktop Found" error. 

I'm sure I'm doing something wrong, can you point me in the right direction?

**Comment by tvrzna** [comment]
`XINITRC_LAUNCH` is meant as prefix for selected desktop (e.g. ~/.xinitrc i3) and it looks like you have empty `/usr/share/xsession/` folder. I recommend to set `XINITRC_LAUNCH` to `false` and create your `~/.config/emptty` file with following content:
```
#!/bin/sh

~/.xinitrc
```

If `~/.config/emptty` file exists, it skips the part, where it checks installed deskop environments.
