### ISSUE TITLE
Looking for ideas

### ISSUE THREAD

**Issue by tvrzna** [tvrzna/emptty#79]
Hello,
there were no commits for few months, the reason is I am out of ideas. No one reports issues, bugs or enhancement-requests and I don't have the feeling I miss something to be developed.
So please, if you have any issue, idea or something to tell/request, please, create an issue or even better create a pull request.

Thank you and have nice holidays!

**Comment by amano-kenji** [comment]
Maybe, it's already close to being complete. I submitted a pull request.
