### ISSUE TITLE
Password entry not working (sometimes) on NixOS - may need more verbose logging?

### ISSUE THREAD

**Issue by the-argus** [tvrzna/emptty#87]
I'm really struggling to reproduce this problem, but sometimes I will be prompted for my password and the input will not swallow all the characters I type. For example, If I see the following:

```
computer login: argus
Password:
```

And then I type ``password123``, I will see the following:

```
computer login: argus
Password: asor23
```

And then (assuming my password is actually password123) I will hit enter, and get an authentication failure. emptty will then quit (I think) and I will be prompted for ``computer login: `` and then ``Password: ``, and then I will be dropped into the tty, as if I had logged into the normal linux tty. During this process, the only thing that emptty logs is the ``Authentication Failure``. Not sure why something like this could happen without causing some more information to be logged.

**Comment by the-argus** [comment]
You can find my emptty module for nixOS [here](https://github.com/the-argus/nixsys/blob/63cf8f699410a71551fffae47a2e270a0cb12b95/modules/emptty.nix) and my emptty package [here](https://github.com/the-argus/nixsys/tree/4d533ce5a5e26f7b1e40183cec387f15279faa4c/packages/emptty). Please note that I am using the package provided by ``wrapper.nix``, because that adds ``getent``, ``mcookie``, and ``xauth`` to path.

**Comment by tvrzna** [comment]
It looks like you have emptty and getty on same TTY. You use TTY1 for emptty, do you have disabled getty service for same TTY?

**Comment by the-argus** [comment]
I think you may be right, getty on that tty was causing the issue where emptty wasn't swallowing all the inputs. I explicitly disabled the getty on the vt by adding the following line in the module's config:

```
    systemd.services."getty@${builtins.toString cfg.configuration.TTY_NUMBER}".enable = false;
    # equivalent to: systemd.services."getty@1".enable = false;
```

It seems to have fixed that problem. However, after typing in my password I get "authentication failure" and emptty crashes, sending me back to the default linux tty login. Maybe I'm not properly disabling getty, though, because I am able to successfully login after that.

**Comment by tvrzna** [comment]
In this case it is difficult to recognize the problem, because it accepts some kind of input and that's all. I don't know, how would I detect something running on same TTY (unless it would scan all /proc/[pid]/fd/ links).

**Comment by the-argus** [comment]
Thank you very much- I believe this was indeed the issue. All keys are being inputted to emptty now.
