### ISSUE TITLE
Emptty does not restart on logout - NixOS

### ISSUE THREAD

**Issue by the-argus** [tvrzna/emptty#88]
I've made further progress on the NixOS module for emptty since my last issue. At the moment, it's working almost completely as expected, (and I'm going to make a PR to nixpkgs!!) but if I quit my windowmanager or log out of gnome (after having launched them from emptty), I am dropped into a tty with nothing but a flashing white underscore in the top left. This is the same behavior that I see whenever I am in a graphical session started by lightdm, and I systemctl stop lightdm.

[My emptty module](https://github.com/the-argus/nixsys/blob/main/modules/emptty.nix)
[My emptty package](https://github.com/the-argus/nixsys/tree/main/packages/emptty)

**Comment by tvrzna** [comment]
It's expected behaviour, emptty does not start itself. Default approach is to restart emptty via init inside [init script](https://github.com/tvrzna/emptty/blob/master/res/systemd-service#L9).

Currently I'm not planning to make it endlessly running by its own.

**Comment by the-argus** [comment]
Ah okay- I figured it was something with my service script. Thanks.
