### ISSUE TITLE
"default" is a very confusing config variable value for Logging / SessionErrLog

### ISSUE THREAD

**Issue by edmonds** [tvrzna/emptty#89]
Hi,

According to the manpage (emphasis added):

> `LOGGING`
> Defines how logging is handled. Possible values are ***"default"***, "appending" or "disabled". ***Default*** value is ***"default"***.

> `SESSION_ERROR_LOGGING`
> Defines how logging of session errors is handled. Possible values are ***"default"***, "appending" or "disabled". ***Default*** value is ***"disabled"***.

The provided config file also has this:

```
# Defines the way, how is logging handled. Possible values are "default", "appending" or "disabled".
#LOGGING=default
```
```
# Defines the way, how is logging of session errors handled. Possible values are "default", "appending" or "disabled".
#SESSION_ERROR_LOGGING=disabled
```

This was very confusing to me because I missed that the default for `SESSION_ERROR_LOGGING` was not `"default"` but instead `"disabled"`.

For these two variables that use the `enLogging` type I would suggest renaming the `"default"` value to `"rotate"` to make the value more descriptive of the behavior and because `"default"` is not necessarily the default.

Thanks!

**Comment by tvrzna** [comment]
Hello,
you are right, it's not only confusing, it's also stupid. It needs to be changed, however backward compatibility needs to be kept.
