### ISSUE TITLE
openrc service should set retry.

### ISSUE THREAD

**Issue by amano-kenji** [tvrzna/emptty#92]
/etc/init.d/transmission-daemon has
```
retry="TERM/45/QUIT/15"
```
/etc/init.d/fancontrol has
```
FANCONTROL_TERMTIMEOUT=${FANCONTROL_TERMTIMEOUT:-"TERM/60/KILL/5"}
retry="${FANCONTROL_TERMTIMEOUT}"
```
so that you can set retry in /etc/conf.d/fancontrol

Something like this should be in emptty openrc service so that `~/.config/emptty` is given enough time to close extra programs.

**Comment by amano-kenji** [comment]
Something like
```
FANCONTROL_TERMTIMEOUT=${FANCONTROL_TERMTIMEOUT:-"TERM/60/KILL/15"}
retry="${FANCONTROL_TERMTIMEOUT}"
```
should be good because it gives emptty a plenty of time to shut down and allows users to configure retry.

**Comment by tvrzna** [comment]
I've tested with Alpine Linux and it seems to be good for handling issues. Thank you for the suggestion.
