### ISSUE TITLE
Set XDG_CURRENT_DESKTOP using DesktopNames= value

### ISSUE THREAD

**Issue by edmonds** [tvrzna/emptty#93]
Hi,

If I understand correctly, there is a key `DesktopNames=` in the desktop entry specification that should be set by the login manager. From https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys:

> `$XDG_CURRENT_DESKTOP` should have been set by the login manager, according to the value of the DesktopNames found in the session file. The entry in the session file has multiple values separated in the usual way: with a semicolon.

It looks like [gdm3](https://sources.debian.org/src/gdm3/43.0-3/daemon/gdm-session.c/#L2701), [lightdm](https://sources.debian.org/src/lightdm/1.32.0-2/src/seat.c/#L991), and [lxdm](https://sources.debian.org/src/lxdm/0.5.3-4/src/lxdm.c/#L1417) all set this environment variable, and I see that some DEs/WMs set the `DesktopNames=` key in their `.desktop` session files, such as [GNOME](https://sources.debian.org/src/gnome-session/43.0-1/data/gnome-wayland.desktop.in.in/?hl=7#L7), [i3](https://sources.debian.org/src/i3-wm/4.22-2/share/xsessions/i3.desktop/?hl=8#L8), [phosh](https://sources.debian.org/src/phosh/0.28.0-2/data/wayland-sessions/phosh.desktop/?hl=7#L7), [icewm](https://sources.debian.org/src/icewm/3.4.0-1/lib/icewm.desktop/?hl=37#L37), [enlightenment](https://sources.debian.org/src/e17/0.25.4-2/data/session/enlightenment.desktop.in/?hl=38#L38), [wayfire](https://sources.debian.org/src/wayfire/0.7.4-3/wayfire.desktop/?hl=7#L7), etc.

Should emptty also read `DesktopNames=` from the session .desktop file and use it to set the `XDG_CURRENT_DESKTOP` environment variable?

Thanks!

**Comment by tvrzna** [comment]
Hello,
that's outstanding research! There is no reason to not implement it, especially with it's just read -> set value.
