### ISSUE TITLE
When shutting down computer, emptty halts for a minute or two and produces ~/core.

### ISSUE THREAD

**Issue by amano-kenji** [tvrzna/emptty#96]
The file size of ~/core is about 51 megabytes.

```
$ gdb emptty core
GNU gdb (Gentoo 13.2 vanilla) 13.2
....
Reading symbols from emptty...

warning: Can't open file /dev/shm/wlroots-EGAnPO (deleted) during file-backed mapping note processing

warning: core file may not match specified executable file.
[New LWP 4426]
[New LWP 4473]
[New LWP 4474]
Core was generated by `Xwayland :0 -rootless -core -terminate 10 -listenfd 27 -listenfd 29 -displayfd'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f034f3ed9fc in ?? ()
[Current thread is 1 (LWP 4426)]
```

**Comment by amano-kenji** [comment]
This seems to be xwayland issue.

**Comment by amano-kenji** [comment]
Reopening because this issue started after upgrading emptty to 0.11.0

**Comment by tvrzna** [comment]
Can you, please, provide more info about your configuration? Because changes between v0.10.0 and v0.11.0 are mostly [superficial](https://github.com/tvrzna/emptty/compare/v0.10.0...v0.11.0). Couldn't it be related to #92, where was a change in OpenRC service requested?

**Comment by amano-kenji** [comment]
```
UID        PID  PPID  C STIME TTY      STAT   TIME CMD
root      3280 19914  0 10:08 tty7     Ssl+   0:00 /usr/bin/emptty -d
```
emptty is already running as root. I think the change to openrc init file could be the cause of the issue. I will investigate.

**Comment by amano-kenji** [comment]
I discovered that after changing
```
EMPTTY_TERMTIMEOUT=${EMPTTY_TERMTIMEOUT:-"TERM/60/KILL/15"}
retry="${EMPTTY_TERMTIMEOUT}"
```
to
```
#EMPTTY_TERMTIMEOUT=${EMPTTY_TERMTIMEOUT:-"TERM/60/KILL/15"}
#retry="${EMPTTY_TERMTIMEOUT}"
```
in openrc init script.
```
rc-service emptty stop
```
fails to kill a sway session, but openrc thinks emptty was stopped.

**Comment by amano-kenji** [comment]
```
EMPTTY_TERMTIMEOUT=${EMPTTY_TERMTIMEOUT:-"TERM/60/KILL/15"}
retry="${EMPTTY_TERMTIMEOUT}"
```

**Comment by tvrzna** [comment]
Seems like any script after starting a desktop (even with Xorg) causes the same issue (e.g. logout from Openbox). Maybe some kind of user exit script would do the thing, if I can't find another solution.

**Comment by amano-kenji** [comment]
If `~/.config/emptty` is a shell script, then the last statement should be `exec "$@"`. Otherwise, emptty fails to kill `~/.config/emptty`.

**Comment by amano-kenji** [comment]
I see two options.

* Move `dinitctl shutdown` to my own scripts executed by keyboard shortcuts.
* Implement user exit script in emptty.

**Comment by tvrzna** [comment]
Currently there is already `DISPLAY_STOP_SCRIPT`, however it's started out of user's session as `root`. So I don't think this would help you. Custom script run by keyboard shortcuts wouldn't handle service termination, so it looks like user exit script is the only way. Also this script should have some short timeout, before it is also terminated (to avoid longer than usual situations).

**Comment by amano-kenji** [comment]
These scripts seem to be able to reboot and power off my computer inside a sway session in response to sway keyboard shortcuts.

my-sway-reboot
```
#!/bin/sh
dinitctl shutdown
sudo my-reboot
```
my-sway-poweroff
```
#!/bin/sh
dinitctl shutdown
sudo my-poweroff
```
`sudo my-reboot` and `sudo my-poweroff` are executed without password.

**Comment by amano-kenji** [comment]
If you want to implement user exit script, I want to be able to configure timeout for the script.

**Comment by tvrzna** [comment]
I'm thinking about this implementation:
- `~/.config/emptty-exit` file
- similar to`~/.config/emptty` it will be shell script with variables, that will be read before execution.
- in this case there will be variable `TIMEOUT` or something like that
- after session finishes (logout, emptty termination, ...), it will check for existance of this file
- if file exists, it will read it for known variables (`TIMEOUT`), if timeout is defined then it will be set, otherwise it will use some short one (5 seconds should be sufficient by default)
- script is executed and kill timout starts
- if timeout is exceeded, script is killed and termination of emptty continues as usual

**Comment by amano-kenji** [comment]
I think that's good enough.
