### ISSUE TITLE
Selection mode: don't ask to choose session if there's only a single option

### ISSUE THREAD

**Issue by tranzystorekk** [tvrzna/emptty#99]
I have a `Selection=true` script and usually only one wm installed, so it feels redundant to have to do additional keypresses just to confirm I want to use it.

**Comment by tvrzna** [comment]
Hi,
that sound logically, however I don't intend to break known behaviour. But I think introduction of `Selection=auto`, which would skip selection if only one WM/DE is available, is good idea! Thank you!

**Comment by tranzystorekk** [comment]
Sounds good, thank you for the interest!
